import { useEffect, useMemo, useState } from "react";

import Header from "./Header";
import Sidebar from "./Sidebar";
import KPICard from "./KPICard";
import JobChart from "./JobChart";
import RecentJobs from "./RecentJobs";
import Jobs from "./Jobs";
import Skills from "./Skills";
import Salary from "./Salary";
import AIAssistant from "./AIAssistant";
import Companies from "./Companies";
import Locations from "./Locations";


import { fetchAllJobs } from "../api";
import {
  computeKPIs,
  jobsByRole as aggregateJobsByRole,
  topSkills as aggregateTopSkills,
  jobsByCity as aggregateJobsByCity,
  jobsByYear as aggregateJobsByYear,
  normalizeRecentJobs,
} from "../utils/aggregate";

const KPI_DEFS = [
  { key: "totalJobs", icon: "briefcase", accent: "purple" },
  { key: "avgSalary", icon: "rupee", accent: "blue" },
  { key: "companies", icon: "building", accent: "teal" },
  { key: "withSkills", icon: "sparkles", accent: "pink" },
];

export default function Dashboard() {
  const [active, setActive] = useState("dashboard");
  const [globalSearch, setGlobalSearch] = useState("");
  const [sidebarOpen, setSidebarOpen] = useState(true);

  const [jobs, setJobs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [reloadToken, setReloadToken] = useState(0);

  useEffect(() => {
    const controller = new AbortController();

    setLoading(true);
    setError(null);

    fetchAllJobs({ signal: controller.signal })
      .then((data) => {
        setJobs(data);
        setLoading(false);
      })
      .catch((err) => {
        if (err?.name === "AbortError") return;
        setError(err?.message || "Something went wrong while loading data.");
        setLoading(false);
      });
 


    return () => controller.abort();
  }, [reloadToken]);
  const generateReport = () => {
  if (!jobs.length) return;

  const salaries = jobs
    .map((job) => Number(job.average_salary))
    .filter((salary) => salary > 0);

  const averageSalary =
    salaries.length > 0
      ? salaries.reduce((sum, salary) => sum + salary, 0) /
        salaries.length
      : 0;

  const highestSalary =
    salaries.length > 0 ? Math.max(...salaries) : 0;

  const companies = new Set(
    jobs
      .map((job) => job.company?.trim())
      .filter(Boolean)
      .filter((company) => company !== "Unknown")
  ).size;

  const skillCounts = {};

  jobs.forEach((job) => {
    if (job.skills && job.skills !== "Not Specified") {
      job.skills.split(",").forEach((skill) => {
        const value = skill.trim();
        if (value) {
          skillCounts[value] = (skillCounts[value] || 0) + 1;
        }
      });
    }
  });

  const topSkills = Object.entries(skillCounts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 10);

  const cityCounts = {};

  jobs.forEach((job) => {
    const city = job.city?.trim();

    if (city && city !== "India" && city !== "Unknown") {
      cityCounts[city] = (cityCounts[city] || 0) + 1;
    }
  });

  const topCities = Object.entries(cityCounts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 10);

  const report = `
JOB MARKET ANALYTICS REPORT
===========================

OVERVIEW
--------
Total Job Postings: ${jobs.length}
Companies: ${companies}
Jobs With Skills: ${
    jobs.filter(
      (job) => job.skills && job.skills !== "Not Specified"
    ).length
  }

SALARY INSIGHTS
---------------
Average Salary: ₹${averageSalary.toLocaleString("en-IN", {
    maximumFractionDigits: 0,
  })}
Highest Salary: ₹${highestSalary.toLocaleString("en-IN", {
    maximumFractionDigits: 0,
  })}
Jobs With Salary Data: ${salaries.length}

TOP SKILLS
----------
${topSkills
  .map(([skill, count], i) => `${i + 1}. ${skill} - ${count} postings`)
  .join("\n")}

TOP CITIES
----------
${topCities
  .map(([city, count], i) => `${i + 1}. ${city} - ${count} postings`)
  .join("\n")}

Generated by Job Market Analytics Platform
`;

  const blob = new Blob([report], {
    type: "text/plain;charset=utf-8",
  });

  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");

  link.href = url;
  link.download = "job_market_report.txt";
  link.click();

  URL.revokeObjectURL(url);
};

  const pageHeading =
    {
      dashboard: "Dashboard Overview",
      jobs: "All Jobs",
      skills: "Skills Analytics",
      salary: "Salary Insights",
      ai: "AI Assistant",
      companies: "Companies",
      locations: "Locations",
    }[active] || "Dashboard Overview";

  const { kpis, jobsByRoleData, topSkillsData, jobsByCityData, jobsByYearData, recentData } =
    useMemo(() => {
      const kpiMap = computeKPIs(jobs);
      const enrichedKPIs = KPI_DEFS.map((def) => ({
        ...kpiMap[def.key],
        icon: def.icon,
        accent: def.accent,
      }));

      return {
        kpis: enrichedKPIs,
        jobsByRoleData: aggregateJobsByRole(jobs, 6),
        topSkillsData: aggregateTopSkills(jobs, 10),
        jobsByCityData: aggregateJobsByCity(jobs, 10),
        jobsByYearData: aggregateJobsByYear(jobs),
        recentData: normalizeRecentJobs(jobs, 6),
      };
    }, [jobs]);

  const totalJobsCount = kpis.find((k) => k.label === "Total Jobs")?.raw ?? 0;
  const heroSubtitle = loading
    ? "Loading latest job postings from the live API..."
    : error
      ? "Could not reach the backend. Use the retry button or confirm FastAPI is running at http://127.0.0.1:8000."
      : `${totalJobsCount.toLocaleString(
          "en-IN"
        )} curated data & AI job postings across India. Understand demand, compensation, and skill trends at a glance.`;

  const retry = () => setReloadToken((v) => v + 1);

  return (
    <div className="jm-app">
      <Header
  active={active}
  onNavigate={setActive}
  onToggleSidebar={() => setSidebarOpen((v) => !v)}
  onSearch={setGlobalSearch}
/>
      <div className="jm-app__body">
        <Sidebar
          open={sidebarOpen}
          active={active}
          onNavigate={setActive}
        />
        <main
  className={`jm-main ${
    active === "jobs" ? "jm-main--jobs" : ""
  } ${
    active === "skills" ? "jm-main--skills" : ""
  } ${
    active === "salary" ? "jm-main--salary" : ""
  } ${
    active === "ai" ? "jm-main--ai" : ""
  } ${
    active === "companies" ? "jm-main--companies" : ""
  } ${
    active === "locations" ? "jm-main--locations" : ""
  }`}
>
          
          
          <section className="jm-hero">
            <div>
              <p className="jm-eyebrow">Analytics · {new Date().getFullYear()}</p>
              <h1 className="jm-hero__title">{pageHeading}</h1>
              <p className="jm-hero__sub">{heroSubtitle}</p>
              {error && (
                <button
                  className="jm-btn jm-btn--primary jm-hero__retry"
                  type="button"
                  onClick={retry}
                >
                  Retry loading data
                </button>
              )}
            </div>
            
          </section>

          {!loading && error && (
            <div className="jm-error jm-error--hero">
              <strong>Could not load from FastAPI backend.</strong>
              <div>{error}</div>
              <div className="jm-error__hint">
                Make sure the backend is running with:
                <code>uvicorn backend.main:app --host 127.0.0.1 --port 8000</code>
              </div>
              <button className="jm-btn jm-btn--primary" type="button" onClick={retry}>
                Retry
              </button>
            </div>
          )}

          <div className="jm-report-bar">
  <button
    type="button"
    className="jm-report-btn"
    onClick={generateReport}
  >
    📄 Generate Report
  </button>
</div>

<section className="jm-kpis">
            {kpis.map((k) => (
              <KPICard key={k.label} kpi={k} loading={loading} />
            ))}
          </section>

          <section className="jm-charts-grid">
            <JobChart
              title="Jobs by Role"
              subtitle="Posting distribution across job titles"
              data={jobsByRoleData}
              loading={loading}
              error={error}
            />
            <JobChart
              title="Top Skills"
              subtitle="Most in-demand technical skills"
              data={topSkillsData}
              loading={loading}
              error={error}
            />
            <JobChart
              title="Jobs by City"
              subtitle="Top 10 cities by number of postings"
              data={jobsByCityData}
              loading={loading}
              error={error}
            />
            <JobChart
              title="Jobs by Year"
              subtitle="Posting volume trend over the years"
              data={jobsByYearData}
              loading={loading}
              error={error}
            />
          </section>

          <section className="jm-recent-wrap">
            <RecentJobs
              jobs={recentData}
              loading={loading}
              error={error}
              onRetry={retry}
            />
          </section>

          <footer className="jm-footer">
            <span>© Job Market Analytics Platform · Portfolio Major Project</span>
            <span className="jm-footer__muted">
              {loading
                ? "Loading from FastAPI backend..."
                : error
                  ? "Using cached UI only — backend unreachable"
                  : `Dataset · ${totalJobsCount.toLocaleString("en-IN")} records · http://127.0.0.1:8000`}
            </span>
          </footer>
          {active === "jobs" && (
  <Jobs jobs={jobs} initialSearch={globalSearch} />
)}
{active === "skills" && <Skills jobs={jobs} />}
{active === "salary" && <Salary jobs={jobs} />}
{active === "ai" && <AIAssistant />}
{active === "companies" && <Companies jobs={jobs} />}
{active === "locations" && <Locations jobs={jobs} />}

          
        </main>
      </div>
    </div>
  );
}
